### ISSUE TITLE
[P2] Limited 10-Orb Bundle can be purchased more than once

### ISSUE THREAD

**Issue by willroberts** [open-duelyst/duelyst#234]
## Summary

The limited "Launch Offer" bundle of 10 Spirit Orbs for 300 Gold is repeatable, making the 10 Orb bundle for 450 Gold redundant. Let's fix or remove the launch offer bundle.

## Impacted services

- [x] The frontend app
- [x] The game servers
- [ ] Game builds or automation scripts
- [ ] Tests or Github Actions
- [ ] Infrastructure (Terraform)

## Steps to reproduce

1. Create an account and log in
2. Click "buy more spirit orbs" from the orbs page
3. Buy the "LAUNCH OFFER" bundle twice

## Environment information

- Operating system: Windows 11
- Browser: Firefox
- Browser version: Latest

**Comment by yoganlava** [comment]
This is due to the spirit orb purchaser not respecting the purchase limit. The code for that is in the old premium purchase code. Just a matter of adding that to the soft spirit orb purchases.
