### ISSUE TITLE
[P0] Missing WebGL hardware acceleration on some Linux systems e.g. Steam Deck

### ISSUE THREAD

**Issue by LiamDawe** [open-duelyst/duelyst#248]
When trying to launch it on Steam Deck when added to Steam, and selecting the compatibility layer to use the Steam Linux Runtime container the game will launch fine but it gives an error about the video card not being supported.

Is there a way to skip this error? As it will likely run on it, most things do just fine.

Ps. I needed to use the Steam Linux Runtime compatibility option (since it's a Native game), as it uses a dependency not included by default (libgconf) on the Steam Deck OS.

**Comment by willroberts** [comment]
Unfortunately I don't have a Steam Deck to test this out. Can you share any screenshots or error messages?

**Comment by LiamDawe** [comment]
Oh yeah I suppose that would have helped woops.
![Screenshot_20230111_144104](https://user-images.githubusercontent.com/83223/211834830-2c2bc2d2-5f2b-45fe-808e-01d2a09a935d.png)

**Comment by willroberts** [comment]
That helps, thanks! Looks like the code in question is right here: https://github.com/open-duelyst/duelyst/blob/1c138df/app/application.coffee#L3857L3892

**Comment by willroberts** [comment]
Out of curiosity, are you able to play in browser at https://staging.duelyst.org ?

**Comment by LiamDawe** [comment]
Ah yeah, I was just hunting for it and found that.

> That helps, thanks! Looks like the code in question is right here: https://github.com/open-duelyst/duelyst/blob/1c138df/app/application.coffee#L3857L3892

Hah yeah was hunting for it and just found it before your comment.

> Out of curiosity, are you able to play in browser at https://staging.duelyst.org ?

With Chrome in Gaming Mode on Steam Deck it does run yes. Obviously the aspect ratio is a bit off right now, quick basic test.

![IMG_3356](https://user-images.githubusercontent.com/83223/211837295-9e629446-b8bf-4f0e-8cbc-8d9a9ee1713a.JPEG)

(Sorry for camera not screenshot, Steam Deck doesn't seem to allow Chrome screenshots to upload to grab it)

**Comment by marwanhilmi** [comment]
Try adding these flags when starting up:
`--enable-accelerated-mjpeg-decode --enable-accelerated-video --ignore-gpu-blacklist --enable-native-gpu-memory-buffers --enable-gpu-rasterization`

Similar issues:
- https://www.reddit.com/r/linux/comments/p2ivtq/updated_guide_on_how_to_get_hardware_acceleration/
- https://thecodersblog.com/hardware-acceleration-in-linux-with-chrome/

**Comment by leios** [comment]
I had this issue on my Arch install and using these flags solved it for me.

**Comment by TinDeve** [comment]
> Try adding these flags when starting up: `--enable-accelerated-mjpeg-decode --enable-accelerated-video --ignore-gpu-blacklist --enable-native-gpu-memory-buffers --enable-gpu-rasterization`
> 
> Similar issues:
> 
> * https://stackoverflow.com/questions/70619124/electron-linux-video-hardware-acceleration
> * https://www.reddit.com/r/linux/comments/p2ivtq/updated_guide_on_how_to_get_hardware_acceleration/
> * https://thecodersblog.com/hardware-acceleration-in-linux-with-chrome/

Confirmed, runs on the Deck with the flags above.

**Comment by willroberts** [comment]
Thanks @marwanhilmi! I'll see if I can get these flags into the Linux build so this "just works" out of the box.

**Comment by willroberts** [comment]
Here's the new release with the hardware acceleration flags added to the Electron build: https://github.com/open-duelyst/duelyst/releases/tag/1.97.11

Let us know if you run into any additional issues!
