### ISSUE TITLE
[P0] Importing a decklist doesnt delete your previous deck/general. Many bugs happen as a result.

### ISSUE THREAD

**Issue by Ein666** [open-duelyst/duelyst#255]
## Summary

When creating a new deck with a general and cards in it you can import a deck with a deckcode containing another General and end up 2 Generals and over 40 cards in your deck.

This has multiple knock-on-effects that add game-breaking bugs like having your bloodbound spell triggering in the corner of the screen rather than around your main general since the second one spawns offscreen.

## Steps to reproduce

1. Create a Duelyst Deck with a general (for example Ragnora the Relentless)
2. Import a decklist with another general of the same faction (for example the decklist below)

MTo0MDEsMjo0MDUsMzo0MTIsMzo0MzMsMjo0MzYsMzo0MzcsMjoxMDk3NSwyOjEwOTgxLDM6MTExMTUsMjoxMTEyMSwzOjE5MDUyLDI6MjAxMTIsMjoyMDExNywyOjIwMTIyLDM6MjAxMjUsMzoyMDE1NywyOjIwMjE4

3. Congratulations, you now have over 40 cards in your deck including 2 generals and playing the game will result in bizarre problems such as:
 - Rendering the second general offscreen so your opponent cannot win after killing your main one.
 - Replacing a card in your hand with your deck will freeze the client
 - Bloodbound spells will only trigger on your off-screen general 

## Environment information

- Operating system: Windows
- Browser: Brave and Native Windows client

## Additional context

![Duelyst_ToesBjsS64](https://user-images.githubusercontent.com/3937981/212408912-3261b5fe-9ab9-41f1-848a-f21e23f97c6f.jpg)
![Duelyst_hRSN7Zg0SP](https://user-images.githubusercontent.com/3937981/212408931-52776430-31e9-48cb-91ac-e7f1f526b03c.png)

**Comment by willroberts** [comment]
Let's see if we can simply hide the Import/Export buttons when a deck is being created or edited. I had only tested this from the main collection page 😅

**Comment by willroberts** [comment]
Relevant buttons: https://github.com/willroberts/duelyst/blob/73299eda0cfa02a18ceaff3c7c6905a6016bf728/app/ui/views2/collection/collection.js#L62L63

Example of hiding the button: https://github.com/willroberts/duelyst/blob/73299eda0cfa02a18ceaff3c7c6905a6016bf728/app/ui/views2/collection/collection.js#L827
