### ISSUE TITLE
[P2] Cannot read property 'availableAt' of undefined

### ISSUE THREAD

**Issue by glystik** [open-duelyst/duelyst#260]
The left menu Play, Collection etc. are missing. After clicking on e.g. Profile, the "Close X" is faded out and doesn't work, unable to go back in menus, even with Esc.

Tried in Chrome, Firefox and Windows, same issues but Firefox has a bit different "Hit a Snag" error: "TypeError: i is undefined"
Chrome: "TypeError: Cannot read properties of undefined (reading 'availableAt')"
Windows: "TypeError: Cannot read property 'availableAt' of undefined"

Maybe it's not related to those issues tho.

**Comment by willroberts** [comment]
This might be related to the old collection gift crate. Are you still experiencing this on staging web?

**Comment by Gsitr** [comment]
> This might be related to the old collection gift crate. Are you still experiencing this on staging web?

Yep, all still same

**Comment by glystik** [comment]
Well nothing has actually changed for my old account created like 3 weeks ago. But making a new account now everything works fine.

**Comment by willroberts** [comment]
@glystik this hasn't been deployed to staging yet, so that make sense. You can also give it a try in local development.
