### ISSUE TITLE
You can build a Deck with less than 40 cards, circumventing deckbuilding restrictions

### ISSUE THREAD

**Issue by Ein666** [open-duelyst/duelyst#266]
## Summary

The game allows you to queue with decks that are less than 40 cards (39+General).

## Steps to reproduce

1. Create a deck with less than 40 cards
2. Queue into a game, either Practice or Ladder.

## Environment information

- Operating system: Windows
- Browser: Brave and Native client

Screenshots below show being in a game with only an 8 card mech deck

![M7Th3tP](https://user-images.githubusercontent.com/3937981/212589601-7f672e6b-887a-4311-8f61-4b8169ed3549.png)
![Duelyst_02LqNIhYMX](https://user-images.githubusercontent.com/3937981/212593172-19eefd94-d430-42e1-a022-dddb6943c88f.jpg)

**Comment by willroberts** [comment]
We were discussing this on the Discord yesterday; it seems to occur due to this line: https://github.com/open-duelyst/duelyst/blob/main/app/ui/models/deck.js#L396

I'll change this today.

**Comment by willroberts** [comment]
Fixed in #268
