### ISSUE TITLE
[CI/CD] Create templates for issues, pull requests, etc.

### ISSUE THREAD

**Issue by willroberts** [open-duelyst/duelyst#40]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by harikanani** [comment]
I would like to work on this issue, Can you please assign it to me? @willroberts

**Comment by willroberts** [comment]
Hi @harikanani , sure thing! Let us know if you have any questions.

**Comment by harikanani** [comment]
> Hi @harikanani , sure thing! Let us know if you have any questions.

I haven't any right now. If I have any further I'll ask. I do have some ideas about which kind of templates can be added, so i'll add that here. Please assign this issue to me.

**Comment by harikanani** [comment]
I have created a [pull request](https://github.com/open-duelyst/duelyst/pull/56) that resolves this issue. I am currently working on many other types of templates too. I'll update that once I complete it.

**Comment by willroberts** [comment]
Sounds good! I think a feature request template and a pull request template would be sufficient here.

**Comment by harikanani** [comment]
I have created another [PR](https://github.com/open-duelyst/duelyst/pull/70) for `feature_request` template
