### ISSUE TITLE
[APP, SERVER] Update Dependencies

### ISSUE THREAD

**Issue by marwanhilmi** [open-duelyst/duelyst#5]
Many dependencies are outdated, have security issues, or are no longer maintained. We'd like to update dependencies while balancing need to work around API compatibility changes.

**Comment by willroberts** [comment]
Something like the free version of [Snyk](https://snyk.io/) could be helpful here, especially for identifying critical security issues before we start deploying servers.

**Comment by willroberts** [comment]
We may also want to consider supplying a separate `package.json` for each service (e.g. `app`, `server`, `worker`) to reduce the number of dependencies per service.

**Comment by willroberts** [comment]
P.S. I'm not sure which change it was exactly, but one of these upgrade PRs has resulted in Firefox support! I'm able to log in and play complete games in Firefox now with no issues.
