### ISSUE TITLE
[CI/CD] GitHub Action Pipelines

### ISSUE THREAD

**Issue by marwanhilmi** [open-duelyst/duelyst#6]
We need to configure various pipelines:
- linting / running unit tests / etc
- managing PRs
- managing deployments for the reference deployment

**Comment by willroberts** [comment]
GitHub Actions for unit testing is complete. The next priorities are Actions for integration testing and linting.

**Comment by willroberts** [comment]
GitHub Actions for linting is complete.

**Comment by willroberts** [comment]
GitHub Actions for integration testing is complete (#47). I'm going to close this and add the reference deployment Actions to the reference deployment issue.
